### ISSUE TITLE
Not run on .net core or netstandard 2.0

### ISSUE THREAD

**Issue by xuan2261** [devpro/withywoods#16]
I am using Visual Studio 2017, and I cannot download this library because I only have the highest .net standard 2.0 installation. Can you move the library down to support .net standard 2.0 or higher? Thank you very much.

**Comment by devpro** [comment]
All libraries have been migrated to .NET Standard 2.1, this is a requirement.

Do you have the latest .NET Core SDK?

You can check it with:

```bash
dotnet --version
# 3.1.101
```

(For information, Visual Studio 2019 works fine, you can use it without any issues!)

**Comment by xuan2261** [comment]
Can you create a version that supports .net standard 2.0? I am using Visual Studio 2017 and I have just configured the device to use VS2017.

**Comment by devpro** [comment]
It's a best practice to be at the latest stable version but it's easy for you to use this version.

You can easily edit the csproj files and update the version here, it will work fine.

```xml
<TargetFramework>netstandard2.1</TargetFramework>
```

I'll be more than happy to have another developer use this library, please let me know if I can help.

**Comment by xuan2261** [comment]
I edit it bit can not install liabrary withywoods. Please check email of me.

**Comment by devpro** [comment]
Email answered.
I close the issue as the solution works with VS 2017.
