### ISSUE TITLE
Testing package upgrade.

### ISSUE THREAD

**Issue by paul-hammant** [devpro/withywoods#284]
Great work on this project and the educations from it :)

Any chance of upgrading `Microsoft.AspNetCore.Mvc.Testing` to v6.0.5 from 5.0.13 ?

It's not a snap - there's a method that's gone: `WebHost.CreateDefaultBuilder(..)`

**Comment by devpro** [comment]
Thank you for the Issue and the positive feedback!
I'm going to update it this WE and ask for your review if you don't mind.

**Comment by paul-hammant** [comment]
Count me in :)  .. I updated the suggested version to 6.0.5 (which I didn't know about til an hour ago).

**Comment by devpro** [comment]
Update made with [v1.5.0](https://github.com/devpro/withywoods/releases/tag/v1.5.0)
