### ISSUE TITLE
chromedriver upgrade

### ISSUE THREAD

**Issue by paul-hammant** [devpro/withywoods#286]
98.0.4758.10200 is a couple of versions out of date now.  

Is there a way to have this more centrally defined?  line "101", just once somewhere?

**Comment by paul-hammant** [comment]
```
find . -type f -name '*.csproj' -exec sed -i '' s/98.0.4758.10200/101.0.4951.64/g {} +
```

... works for me locally (Mac)

**Comment by devpro** [comment]
Thank you for the issue!

Yes, it's an old version, I'll update it in the Pull Request.

**Comment by devpro** [comment]
Update made with [v1.5.0](https://github.com/devpro/withywoods/releases/tag/v1.5.0)
